name: Java CI

on:
  push:
    branches:
      - main
      - feature-*

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Check Java Version
        run: java -version

      - name: Compile Java Program
        run: javac src/*.java

      - name: Run Tests
        run: java -cp src TestCalculator
