<<<<<<< HEAD
name:  My fist CI
=======
name: My first CI
>>>>>>> parent of ecba7fb (Add Github Action workflow)

on:
    push:
        branches:
            - main
            - feature-*
    pull_request:
        branches:
            - main

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            
            - name: Checkout Repository
              uses: action/checkout@v4

            - name: Print Message

            -  run: echo "Hello from Github Actions!" 

